from django.shortcuts import render
from .models import Grupo
from .forms import GrupoForm
import pandas as pd


# View to register a group using a xlsx file   
def registro_grupo(request):
    if request.method == 'POST':
        form = GrupoForm(request.POST, request.FILES)
        #import pdb; pdb.set_trace()
        if form.is_valid():
            file = request.FILES['file']
            df = pd.read_excel(file, skiprows=range(0, 11), usecols=[0,1,2,3,4,5,6])# skips first 11 rows and only uses columns 0 to 6
            table = df.to_html(index=False)#index False to avoid showing the index column(generated by pandas)
            form.save()
            return render(request, 'panditaslectores/lista_grupo.html', {'table': table})
    else:
        form = GrupoForm()
    return render(request, 'panditaslectores/registro_grupo.html', {'form': form})
    

